### ISSUE TITLE
Typo in --gcp_credential_path in readme.md

### ISSUE THREAD

**Issue by mcshicks** [bgutter/voicenotes2org#1]
I think it should be --gcp_credentials_path (add an s at the end)

usage: voicenotes2org [-h] [--voice_notes_dir VOICE_NOTES_DIR]
                      [--archive_dir ARCHIVE_DIR]
                      [--org_transcript_file ORG_TRANSCRIPT_FILE]
                      [--just_copy JUST_COPY]
                      [--gcp_credentials_path GCP_CREDENTIALS_PATH]
                      [--verbose VERBOSE]
                      [--max_concurrent_requests MAX_CONCURRENT_REQUESTS]
                      [--voicenote_filename_regex_path VOICENOTE_FILENAME_REGEX_PATH]

**Comment by bgutter** [comment]
Fixed in bcda948b6cf311820f9827938161dc3ab0c3ee1b, thanks!

Also updated the README to encourage installs from Github sources, rather than PyPI. The PyPI code is a bit outdated right now.

Feel free to let me know if you have any troubles getting it to work; I didn't dedicate much time to properly packaging this.
